#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  1 23:33:55 2017

@TO 20170201, 20260507
"""

# %% === imports
import os 
import sys

sys.path.insert(0, '/Users/Theo/Development/python/hydro_tools/')

import re
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
from KNMI_data_from_URL import Weather_stn

from tools.coords import wgs2rd

# %% === Definitions
class Dirs:
    """Namespace for the directories of this project."""
    def __init__(self):
        self.home = '/Users/Theo/Development/python/hydro_tools/tools/KNMI/'
        self.data = os.path.join(self.home, 'data')
        self.src  = os.path.join(self.home, 'src')
        self.notebooks = os.path.join(self.home, 'notebooks')


def knmi_stations(statonsFile):
    """Return the KNMI stations given the tile downloaded from the KNMI site.
    
    file name in folder
    -------------------
     KNMI/data: 'KNMI_weerstations_meta.txt'
     
    Method
    ------
    The file read and scanned using a few regex lines.
    Code generated by chatGPT with minor adaptations.
    
    @TO 20260507
    """
    # --- Read the file as a single string!
    with open(stationsFile) as f:
        text = f.read()

    # --- Split into station blocks
    blocks = re.split(r'=+\n', text)

    # --- Then start the stations dictionary
    stations = {}

    # --- Run over the blocks to analyze each of them individually
    for block in blocks:
        # --- Remove leading and trailing whitespace
        block = block.strip()

        # --- Skip first last or empty blocks
        if not block or 'coordinates:' not in block:
            continue

        # --- Split the current block
        lines = block.splitlines()

        # --- Get the station name
        name = re.sub(r'\s+\(.*\)', '', lines[0]).strip()

        # --- GEt the station coordinates
        m = re.search(
            r'coordinates:\s*'
            r'([\d.]+)N,\s*'
            r'([\d.]+)E,\s*'
            r'([-\d.]+)m',
            block
        )

        # --- Retrieve lat long and alt from coordinates
        lat = float(m.group(1))
        lon = float(m.group(2))
        alt = float(m.group(3))
        
        xRD, yRD = wgs2rd(lon, lat)

        # --- Station code
        m = re.search(r'station code:\s*(\d+)', block)
        code = int(m.group(1))

        # --- Data years
        m = re.search(
            r'Found\s+(\d+)\s+years with data in\s+(\d+)-(\d+)',
            block
        )

        nyears = int(m.group(1))
        start_year = int(m.group(2))
        end_year = int(m.group(3))

        stations[code] = {
            'name': name,
            'lat': lat,
            'lon': lon,
            'xRD': np.round(xRD),
            'yRD': np.round(yRD),
            'alt': alt,
            'nyears': nyears,
            'start_year': start_year,
            'end_year': end_year,
        }
    
    # --- Return as dictionary
    return stations


# %%
if __name__ == '__main__':
            
    dirs = Dirs()

    # --- Switch to home directory (may not be necessary)
    os.chdir(dirs.home)

    
    stationsFile = os.path.join(dirs.data, 'KNMI_weerstations_meta.txt')
    # --- Parse the stations file into a dict    
    
    stations = knmi_stations(stationsFile)
    # --- Turn it into a pd.DataFrame
    stations = pd.DataFrame(stations).T
    
    # --- Show the stations
    fig, ax = plt.subplots()
    
    ax.plot(stations['xRD'], stations['yRD'], 'ro')
    
    # --- Add station names
    for idx in stations.index:
        st = stations.loc[idx]
        ax.text(st['xRD'], st['yRD'], f" - {idx} {st['name']}",
                va='center', ha='left', fontsize=6)

    # --- Finish the plot
    ax.set_title("Weerstations KNMI")
    ax.set(xlabel='xRD [m]', ylabel='yRD [m]')
    ax.grid()
    ax.set_aspect(1)
    ax.legend()
    
    
    # %% === Show the neerslag stations

    # --- Get the data file
    fname = os.path.join(dirs.data, 'KNMI_neerslagstations_mei2021_1d.csv')
    
    # --- Read it into a pd.DataFrame
    stns = pd.read_csv(fname)
    
    # --- Show part of it
    print(stns.head)
    
    # --- Show the stations
    fig, ax = plt.subplots()
    
    ax.plot(stns['STN_POS_X'], stns['STN_POS_Y'], 'ro', label='Neerslagstations')
    
    # --- Add the station names (becomes a mess, but ok)
    for idx in stns.index:
        stn = stns.loc[idx]
        ax.text(stn['STN_POS_X'], stn['STN_POS_Y'], f" -- {stn['LOCATIE']}",
                ha='left', va='center', fontsize=6)
    
    # --- Finish off
    ax.set_title(f"KNMI neerslagstations, aantal ={len(stns)}")
    ax.set(xlabel='xRD [m]', ylabel='yRD [m]')
    ax.set_aspect(1)
    ax.grid()
    ax.legend()
    
    # %% === Show how to get KNMI data

    # --- Specify a period using KNMI way of defining dates
    start = "20160101"
    end   = "20200101"

    # --- The most pythonic way to convert these into timestamps
    xlim = pd.to_datetime((start, end), format='%Y%m%d')

    # --- A few KNMI weather stations
    stnGilze  = 350 
    stnEelde  = 280 
    stnDeBilt = 260

    # --- Get the weather data from KNMI
    gilzeRijen = Weather_stn(what='weather',
                    start=start, end=end,
                    stns=stnGilze, folder=dirs.data).df
    
    # --- Same for Eelde
    eelde = Weather_stn(what='weather',
                    start=start, end=end,
                    stns=stnEelde, vars=['RH', 'EV24', 'P'], folder=dirs.data).df
    
    # --- Example requesting hourly data for some fields
    #     The fields must exist, else a result.ok->false, error 500 is returned.
    #     This possibly overwrites an existing file with other data.
    dBilt = Weather_stn(what='hourly',
                    start=start, end=end,
                    stns=stnDeBilt, vars=['RH', 'P'], folder=dirs.data).df

